version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/deadmau5v/LoongPanel"

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[patterns]
tests = [
  "test/**",
  "integration_tests/tests_*.py",
  "**/*_test.go"
]
excluded = [
  "migrations/**",
  "/dist/*min.js"
]