name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build name
        run: |
          BUILD_NAME="LoongPanel-$(date +'%Y-%m-%d-%H:%M:%S')"
          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV

      - name: Build and Publish
        run: |
          echo "Building and publishing $BUILD_NAME"
          sh build.sh
