on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 构建
        run: |
          pwd
          chmod +x build.sh
          sh build.sh

      - name: 发布
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.sha }}
          tag: ${{ github.sha }}
          body: ${{ github.sha }}

